apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-check
  labels:
    app: http-check
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: http-check
  template:
    metadata:
      labels:
        app: http-check
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.1@sha256:ecc068890de55a75f1a32cc8063e79f90f0b043d70c5fcf28f1713395a4b3d49
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
      - name: network-health-http
        image: ghcr.io/damoon/network-health-sidecar:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
