apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-check
  labels:
    app: http-check
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: http-check
  template:
    metadata:
      labels:
        app: http-check
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.2@sha256:e209ac2f37c70c1e0e9873a5f7231e91dcd83fdf1178d8ed36c2ec09974210ba
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
      - name: network-health-http
        image: ghcr.io/damoon/network-health-sidecar:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
