apiVersion: apps/v1
kind: Deployment
metadata:
  name: exec-check
  labels:
    app: exec-check
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: exec-check
  template:
    metadata:
      labels:
        app: exec-check
    spec:
      containers:
      - name: nginx
        image: nginx:1.22.0@sha256:d4fe835ca959ff06f3f0d6fff47dc9d480d21179cefea413f07e1be6b1de16c3
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
      - name: network-health-exec
        image: ghcr.io/damoon/network-health-sidecar:latest
        args:
        - --protocol=unix
        - --addr=/tmp/network-health.socket
        readinessProbe:
          exec:
            command:
            - network-health-client
            - --protocol=unix
            - --addr=/tmp/network-health.socket
