apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-check
  labels:
    app: http-check
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: http-check
  template:
    metadata:
      labels:
        app: http-check
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.1@sha256:2f770d2fe27bc85f68fd7fe6a63900ef7076bc703022fe81b980377fe3d27b70
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
      - name: network-health-http
        image: ghcr.io/damoon/network-health-sidecar:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
