apiVersion: apps/v1
kind: Deployment
metadata:
  name: exec-check
  labels:
    app: exec-check
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: exec-check
  template:
    metadata:
      labels:
        app: exec-check
    spec:
      containers:
      - name: nginx
        image: nginx:1.31.6@sha256:908dc23e643a1447dbfb2e189ed268bfde6a51a5bf9a34d3dd3440a24f58ccf7
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
      - name: network-health-exec
        image: ghcr.io/damoon/network-health-sidecar:latest
        args:
        - --protocol=unix
        - --addr=/tmp/network-health.socket
        readinessProbe:
          exec:
            command:
            - network-health-client
            - --protocol=unix
            - --addr=/tmp/network-health.socket
