apiVersion: apps/v1
kind: Deployment
metadata:
  name: exec-check
  labels:
    app: exec-check
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: exec-check
  template:
    metadata:
      labels:
        app: exec-check
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.4@sha256:1f105601bfded0fa298d8c5efd5569f4ed3bf53dc7f4c41c691c29999550f6a3
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
      - name: network-health-exec
        image: ghcr.io/damoon/network-health-sidecar:latest
        args:
        - --protocol=unix
        - --addr=/tmp/network-health.socket
        readinessProbe:
          exec:
            command:
            - network-health-client
            - --protocol=unix
            - --addr=/tmp/network-health.socket
