apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-check
  labels:
    app: http-check
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: http-check
  template:
    metadata:
      labels:
        app: http-check
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.3@sha256:b8f2383a95879e1ae064940d9a200f67a6c79e710ed82ac42263397367e7cc4e
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
      - name: network-health-http
        image: ghcr.io/damoon/network-health-sidecar:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
