apiVersion: apps/v1
kind: Deployment
metadata:
  name: exec-check
  labels:
    app: exec-check
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: exec-check
  template:
    metadata:
      labels:
        app: exec-check
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.6@sha256:2834dc507516af02784808c5f48b7cbe38b8ed5d0f4837f16e78d00deb7e7767
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
      - name: network-health-exec
        image: ghcr.io/damoon/network-health-sidecar:latest
        args:
        - --protocol=unix
        - --addr=/tmp/network-health.socket
        readinessProbe:
          exec:
            command:
            - network-health-client
            - --protocol=unix
            - --addr=/tmp/network-health.socket
