apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-check
  labels:
    app: http-check
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: http-check
  template:
    metadata:
      labels:
        app: http-check
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.4@sha256:6db391d1c0cfb30588ba0bf72ea999404f2764febf0f1f196acd5867ac7efa7e
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
      - name: network-health-http
        image: ghcr.io/damoon/network-health-sidecar:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
