apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
      - name: network-health-http
        image: network-health-image
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
      - name: network-health-exec
        image: network-health-image
        command:
          - network-health-server
          - --protocol=unix
          - --addr=/tmp/network-health.socket
        readinessProbe:
          exec:
            command:
              - network-health-client
              - --protocol=unix
              - --addr=/tmp/network-health.socket
